### ISSUE TITLE
Add NATS support

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#1]
Add support for NATS as an input and as an output. 

http://nats.io/
https://github.com/nats-io/gnatsd

**Comment by joeblew99** [comment]
I came here to make an issue for this . You read my mind.

I am really interested in benthos. It's a highly useful / practical thing.

I am also interested is using flogo ( on github ) with benthos.
They both compliment each other very nicely.

Flogo is interesting in that you described a flow and can then compile it to golang.

I am also thinking that all these systems need to hook into a service discovery system such as etcd so that when an endpoint changes they adapt.
Flagz on github can do this without the using process restarting 

Since your using this for real world stuff am curious of your opinions

**Comment by Jeffail** [comment]
Hey @joeblew99, I haven't seen flogo before but I'll check it out, sounds interesting. Etcd support would be great, I hadn't initially planned for it so at this stage it might take me a while to consider how I'd integrate it.

**Comment by joeblew99** [comment]
@Jeffail thanks !!
