### ISSUE TITLE
Text transform bug

### ISSUE THREAD

**Issue by Tapuzi** [Jeffail/benthos#1006]
Seems like in some cases the input is translated to `base64` and in some it isn't. 
Specifically: textual input is transformed to `base64` when `json` output is used, not with `plaintext`.

Benthos version: `v3.60.1`

Visual example:
![image](https://user-images.githubusercontent.com/5293751/145687919-972466a7-64e8-43cd-b3a8-366fa32d50c6.png)

Reference:
```
Input: testTEST
---
root.a = content().string().uppercase()
Output:
{
  "a": "TESTTEST"
}
---
root.a = content().uppercase()
Output:
{
  "a": "VEVTVFRFU1Q="
}
---
root = content().uppercase()
Output:
TESTTEST
```

**Comment by packman80** [comment]
It's documented behaviour 

> Returns the full raw contents of the mapping target message as a byte array. When mapping to a JSON field the value should be encoded using the method encode, or cast to a string directly using the method string, otherwise it will be base64 encoded by default.

https://www.benthos.dev/docs/guides/bloblang/functions#content

**Comment by Jeffail** [comment]
Yeah this is unfortunate but expected behaviour, the return from `content` is arbitrary data so there's no guarantee that it can be safely represented as a raw JSON string.

When you assign it to the root you're fine because Benthos supports binary messages, and then when it's written to stdout or anywhere else you see the raw data. However, when you set a structured field to binary data it eventually gets JSON formatted, which encodes the field value as a base64 string.

**Comment by Tapuzi** [comment]
Thank you both for the time.
I thought I spotted a bug, now I see what this is about.
