### ISSUE TITLE
Batch processor › We need better logic for period checking

### ISSUE THREAD

**Issue by andytruong** [Jeffail/benthos#108]
The problem is explained below:

![20180919_103748](https://user-images.githubusercontent.com/41143/45729800-6a081c00-bbf8-11e8-8588-b25e7ae3eebb.jpg)

That batch::ProcessMessage() is only executed if there's some message published into the queue.

Instead of that, I suggest we move the flushing logic  into batch::flush(), and we run an other goroutine to check period time.

**Comment by Jeffail** [comment]
Hey @andytruong, can you explain more about your use case? Normally I would expect a continuous stream of data, it looks as though you are expecting bursts of messages and need to batch messages by that burst, what's the ultimate goal here?

Unfortunately due to the limitations of a processor type we can't introduce this within the `batch` processor without breaking the resiliency guarantees within Benthos.

There's possibly a way of doing this with a `batch` input type, similar to the `read_until` input type but it would take a lot of effort to ensure there are no edge cases where acknowledgement propagation is broken. I wouldn't be interested in making that effort without a strong and common use case to support it.

**Comment by andytruong** [comment]
> Normally I would expect a continuous stream of data…

We are developing an application for user to import data, the number of records is unexpected, it can be 500, 800, 1k or 10k. When the uploaded the csv file, I can't sure when is the next message; can be days. So that with current structure of Benthos, in theory, my messages can be hang for long time.

Thanks for your fast feedback.

**Comment by Jeffail** [comment]
Hey @andytruong, whats the purpose of the batching? Is it more than just improving throughput? I've thought through my options here and I can't see a reasonable way of supporting this use case without intentionally adding mechanisms to break the delivery guarantees within Benthos, which I'm not prepared to do.

**Comment by andytruong** [comment]
Hi Jeff,

Thanks again for your comment. We are having around the Benthos wrapper ^^

**Comment by Jeffail** [comment]
Hey @andytruong, just as a follow up, I've refactored batching in Benthos in v3.3.0, it's now much more flexible (for all inputs): https://docs.benthos.dev/batching/

**Comment by andytruong** [comment]
<3
