### ISSUE TITLE
S3 Download errors should report the bucket and key

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#152]
When the `s3` input fails to download a key N times it will move on after logging the error. The logs currently report the specific error but not the bucket or key, which is important information for diagnosing issues and should therefore be included.

**Comment by Jeffail** [comment]
Also while doing this I'm going to add some more metadata fields (ContentType, LastModified, etc).

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/2aca31a221393a4acaff3fc08f0c0c78eef070e4

**Comment by fbabin** [comment]
The log creates an extra line that creates 2 cloudwatch logs instead of one. Line breaks at "status code":
{"@timestamp":"2019-01-29T10:01:48-08:00","@service":"swagfiend","level":"ERROR","component":"swagfiend.input","message":"Failed to read message: failed to download file '/run3/1ZBRqfWKbQb94FCBabga7uL50Yo.json' from bucket 'sig-nlp-lake-stg-eu-west-1': NoSuchKey: The specified key does not exist.
        status code: 404, request id: 515881EB41B9C6B9, host id: fDtnCNQ4tb8XJI1djm3jDSdvsSiwAMD9uCcxYwreOMLnlXe6ZpW4nLqWHTpzEdrdnviG8IFhgmE=\n"}
