### ISSUE TITLE
Nats Stream Unsubscribe deletes offset

### ISSUE THREAD

**Issue by thinktainer** [Jeffail/benthos#161]
When the last member of a queue group in the nats_stream input goes away, the [unsubscribe call](https://github.com/Jeffail/benthos/blob/master/lib/input/reader/nats_stream.go#L112) will destroy the offset for that subscription. See: https://github.com/nats-io/go-nats-streaming#closing-the-group.
For me this was surprising behaviour. My expectation would be that when setting up a durable queue subscription the offset should survive all consumers of the group leaving. Can you clarify your position on this, and if you agree with my expectation talk about alternatives?

**Comment by Jeffail** [comment]
Hey @thinktainer, interesting. From what I can see it would be safe to add a boolean config field like `unsubscribe_on_close`, and if set to false would simply not unsubscribe on connection close.

In order to avoid changing the existing behaviour it would need to be `true` as default to begin with, but if it's unintuitive for it to behave this way (which I agree, it is) then we can have it set to `false` by default in the next major release.

Does that seem sensible to you? I'm not currently using NATS in production so I'm not 100% sure.

**Comment by thinktainer** [comment]
I'm finding myself in a weird place where i want to move off of nats, but still have to keep things ticking over until that time. I think your proposal is spot on. Do you want me to implement, or are you happy enough doing it yourself? (seeing that your turnaround is about the speed of light..., thank you!)

**Comment by Jeffail** [comment]
I'm happy to do it later today

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/ee0e47cbedb45d09f032eade21e98f98ea258fcc

**Comment by thinktainer** [comment]
amazing, ty

**Comment by thinktainer** [comment]
Thank you for remembering!
