### ISSUE TITLE
graceful shutdown question

### ISSUE THREAD

**Issue by fbretel-cn** [Jeffail/benthos#173]
Hi. I'm loving benthos! Been playing with instances piping from rabbitmq to kafka. Noticed that slightly more messages were received when doing a rolling update. This got me thinking about the origin of the discrepancy. My hypothesis so far is that benthos' graceful shutdown being propagated
  from the input layer to the output layer, we could have the case where dying instances would  have committed to kafka but not be able to ack to rabbit anymore. @Jeffail does that sound plausible ?
If so shouldn't benthos shutdown in the reverse order ?

**Comment by Jeffail** [comment]
Hey @fbretel-cn, yes I think you're correct. During shutdown it's possible that while a message is in transit whilst the input layer is closed down that the component is terminated before the acknowledgement can propagate back to the input source.

The reason we shut down from the input layer to the output layer is because of input sources that don't support acknowledgements. If we were to close the output layer first whilst consuming, say, a nanomsg socket then it's very likely that messages will be dropped during every restart.

However, the duplicates you're seeing are actually avoidable and can be traced back to here: https://github.com/Jeffail/benthos/blob/master/lib/input/reader.go#L213. 

If the input layer is told to terminate whilst a message is in transit then it immediately closes without waiting for the acknowledgement. This could be seen as an optimization in shutdown time at the expense of introducing duplicates, which on review seems incorrect. We have an ungraceful termination fallback in the event of messages blocked at the output layer so it doesn't harm behavior if I remove this.

I've created a new ticket for addressing this: https://github.com/Jeffail/benthos/issues/174

**Comment by fbretel-cn** [comment]
Waow! Thank you for the fast and detailed answer and follow-up ticket :+1:

**Comment by Jeffail** [comment]
No problem, thanks for raising this issue! It should now be fixed in [v1.7.10](https://github.com/Jeffail/benthos/releases/tag/v1.7.10). I've added a grace period of one second for in-transit messages to be resolved which should be enough for rolling restarts of healthy pipelines.
