### ISSUE TITLE
question on new batch restriction: only for input

### ISSUE THREAD

**Issue by scotthew1** [Jeffail/benthos#214]
we recently tried to upgrade benthos and noticed that `--strict` now fails because we have batches setup within our pipelines rather than on the input. i'm generally happy to reconfigure our pipelines, but we have some custom processors we'd need to refactor a bit to work with batched messages.

the new documents simply state
> The batch processor should always be positioned within the input section - ideally before any other processor - in order to avoid unexpected acknowledgment behaviour and message ordering.

which isn't very specific about the potential issues. are there any additional details you can provide that motivate this recommendation? what sort of unexpected ack behavior can occur with a batch in the middle of our pipeline? (we don't really care about ordering at all)

**Comment by Jeffail** [comment]
Hey @scotthew1,

Sorry for the wall of text here, it would be great to try and edit/shorten this and put it within the documentation somewhere.

## Explanation

When an input receives a message batch and sends it down the pipeline it blocks acknowledgement of the batch until it receives a response, which could be from any component (processor, buffer, or output.) During this time it's possible for the input to continue consuming messages in the background ready for the next batch, but it won't actually send another batch through Benthos until the response has been received for the previous one.

A response is traditionally either an acknowledgement (ack) or not (noack), and the input is responsible for propagating that response back to the message source according to its protocol.

However, this is a problem for the `batch` processor, as it wants to store messages and continue reading them until the batch is large enough. The `batch` processor must therefore send a response back to the input in order to receive more messages, but it can't send an acknowledgement since the messages haven't ended up anywhere yet, it also can't send a noack since that would cause the same messages to be retried.

Instead, the batch processor sends a third response type supported by Benthos called an unack (unacknowledgment), this is an indicator that the message batch from the input has been 'dealt' with for now and we would like to receive more, but it is important NOT to acknowledge the messages yet.

The input interprets an unack differently depending on the protocol, but usually it means send more messages without acknowledging the previous and keep a reference to all pending acknowledgements. With Kafka, for example, it would simply not commit the offsets for those messages and send another batch.

An input will continue doing this for as long as unack responses are received. Until, eventually, the `batch` processor reaches its goal size, sends the batch down the rest of the pipeline, and a response gets routed to the input, most likely from an output. When the input finally receives either an ack or a noack it applies that response to all pending messages at the same time.

Because of this pattern it's very important that a `batch` processor is always directly linked with exactly one input. This pattern is broken in any of the following example arrangements:

1. N inputs writing into M `batch` processors within a pipeline section where N > 1 and/or M > 1.
2. An input writing into a `filter` processor followed by a `batch` processor, as it would be possible for the filter to return an ack on a filtered message when preceeding messages are within a batch waiting to be sent somewhere and inappropriate to acknowledge.

Although the real life impact of these arrangements is minimal, and most likely won't cause message loss in a typical stream pipeline, it's not possible to _guarantee_ at-least-once delivery and therefore should be avoided.

You can guarantee that neither of these problematic arrangements occur when you configure a batch processor first within the input section, as processors configured in this section are always coupled with exactly one input even when using a `broker`. The `batch` processor is unique in that it is the only processor able to respond with `unack`, and therefore it is the only one that has this linting rule.

## Solution

If you're able to update your processors to work on batches of multiple messages then that's great, but alternatively you can place your processors within a [`for_each`](https://docs.benthos.dev/processors/#for_each) processor, which simulates running the child processors on single messages. For example, if you currently had:

``` yaml
pipeline:
  processors:
  - type: fooproc
    plugin:
      bar: baz
  - type: batch
    batch:
      count: 10
```

You could potentially change to:

``` yaml
input:
  processors:
  - type: batch
    batch:
      count: 10

pipeline:
  processors:
  - type: for_each
    for_each:
    - type: fooproc
      plugin:
        bar: baz
```

Without having to modify your custom processors at all.

**Comment by scotthew1** [comment]
hey @Jeffail thanks for such a detailed explanation! we've definitely been guilty of sending an input to multiple batch processors. will give you solutions a try.

**Comment by Jeffail** [comment]
Hey @scotthew1, closing this for now, feel free to reopen if you have more questions.
