### ISSUE TITLE
Benthos writing directly to cassandra

### ISSUE THREAD

**Issue by adamwasila** [Jeffail/benthos#250]
So here is the thing - I'm evaluating benthos as a possible replacement of stack of connectors and processors using flink. Mostly because processing is quite trivial and memory overhead of flink cluster is pretty insane so benthos looks like a natural fit.

My pipeline is kind of ETL, where I read from several external sources (queues, http) transform data and write it to kafka, then I read it from kafka again and upload it to cassandra database. It is quite trivial to replace first stage with benthos but for second stage I would need to write custom sink for cassandra which apparently isn't yet implemented.

But before I start, my questions are:
  - is it already planned by someone? Maybe we could join our efforts to write & test one? It would help to make it more generic (more use cases) and performant.
  - should it be output (like for `redis`) or processor (like `sql`)? BTW, why is `sql` not an output anyway?
  - would you consider adding it to the benthos if I ever made it 'production ready' or public plugin is my way to go?

**Comment by Jeffail** [comment]
Hey @adamwasila, sounds like a good fit. I'm not aware of any other efforts to write a cassandra connector.

There are three component types that would potentially suit a cassandra implementation which are cache, processor and output.

Writing a cassandra cache component would allow it to be used with the `cache` processor as well as other components but probably doesn't suit your particular use case.

Writing a cassandra processor allows it to be used for both a storage and queries. For example, the reason `sql` is currently only implemented as a processor is so that it could be used to enrich documents before sending them to a conventional output. But if you only wanted to write to a DB and nothing else you can still do that by following it with a `drop` output type.

Writing a cassandra output is also useful and saves you from having to build it to support queries, it'd be a simpler implementation.

I'd be happy to accept a PR for any of these component types.

**Comment by adamwasila** [comment]
Thanks for clarifications. I've decided to start with output first. My prototype handles happy path and seems to work flawlessly. Cassandra has this beautiful construct "INSERT INTO .. JSON" which makes it straighforward and saves from binding and type casting hell. All datatypes are supported using that syntax (except counters which I haven't tested yet).

Biggest surprize so far was that in benthos all errors are equal in terms of significance. There seems to be no difference between 'possibly retryable' and 'possibly fatal' kinds of error. In a result, output cannot categorize if request is worth retrying (eg. sudden disconnection) or not (error suggesting that schema is incompatible). But I guess that is kind of architecture choice, I can live with that.

The only problem so far is that it is not possible to use function call (eg. to generate timeuuid on cluster side using `now()` function) as explained here: https://issues.apache.org/jira/browse/CASSANDRA-12051 . It seems that there is no easy workaround over this issue - I don't want to use regular `INSERT INTO ... VALUES` statement because making a correct binding is really non trivial without knowing schema in advance.

In a result calling functions is currently out of scope, later I'll try to implement some interpolation function to generate timeuuid on service side - that should fulfil most use cases I think.

So far it looks quite promising and my first PR should be ready in few days.

**Comment by Jeffail** [comment]
Hey @adamwasila, yeah in the case where you have non-retry worthy errors just return them as normal. It's possible to add output level retry fields like with the dynamo db output, where in the event of a non-temporal error you would immediately return the error, but otherwise follow the configured retry logic. That allows a user to drop data on the non-temporal errors with a `drop_on_error` parent output. However, that's something that can be added later.

**Comment by adamwasila** [comment]
As you may see work on this feature has stalled. There is working proof of concept on my fork of benthos here: https://github.com/adamwasila/benthos/tree/WIP_output_cassandra . Works quite well but it lack proper testing, especially benchmarks (and correctness check!) under heavy load. If anyone wants  to take over it, feel free. From my side, I won't give you any hard promises now, but if my "business reasons" return I'll continue from where I left it in Q1/2020.

**Comment by Jeffail** [comment]
@adamwasila, sounds good, thanks for your contributions so far. I'll flag this as help wanted but if it doesn't go anywhere then I'll get it finished up eventually.

**Comment by Jeffail** [comment]
Thanks @adamwasila and @codingconcepts! Finally got this one over the finish line :rocket:

**Comment by codingconcepts** [comment]
Woop! Thanks for merging, @Jeffail 🙌

When you get a mo, would you mind pushing a new Docker image please?
