### ISSUE TITLE
Versioning issues

### ISSUE THREAD

**Issue by asiragusa** [Jeffail/benthos#264]
Hi @Jeffail, while updating benthos in my projects I noticed that there is an issue with the `go.mod` versioning. 

If I set `v2.12.2` in my `go.mod`, the version is replaced by go with `github.com/Jeffail/benthos v0.0.0-20190819201742-625538b730ba` (the release date and sha1 of the 2.12.2 branch). After digging the issue out, I found this doc that explains how to create a major release: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher 

The least I can say is that I am VERY surprised :)

**Comment by Jeffail** [comment]
Hey @asiragusa, Benthos currently _uses_ go modules, but doesn't _support_ modules due to this. You can pull a specific version with `go get github.com/Jeffail/benthos@v2.12.2`, but you'll see the ugly hash in your `go.mod`. The current plan is to release v3 once modules are the default global behaviour in Go, and at that point I'll also follow all the correct measures for supporting modules.

There's more info about why I didn't go fully into modules during the v2 bump here: https://github.com/Jeffail/benthos/issues/232
