### ISSUE TITLE
Bump brew & docker versions from v3.2.0

### ISSUE THREAD

**Issue by stephanebruckert** [Jeffail/benthos#311]
Great to see there is a new `json_schema` condition released in v3.3.0!

https://github.com/Homebrew/homebrew-core/blob/master/Formula/benthos.rb and https://hub.docker.com/r/jeffail/benthos/tags need updates (currently v3.2.0)

Thank you

**Comment by Jeffail** [comment]
Hey @stephanebruckert, the docker tags are automated and it looks like they've been kept up to date from my end. I'm not entirely sure what is needed for updating the homebrew formula but hopefully someone can help us out. It would be nice to automate it if possible

**Comment by DpoBoceka** [comment]
Hey. The ability to create a PR from brew under linux was added with this: https://github.com/Homebrew/brew/pull/6718
So, you just need to execute something like

> brew bump-formula-pr --strict benthos --url=https://github.com/Jeffail/benthos/archive/v3.7.0.tar.gz

in order to update formula to 3.7 version, if it is already on a github.
There is more information regarding creating PR from brew in the manual page of it, under tag bump-formula-pr. So, I suspect, you just need to append your drone.yaml with that command. Keep in mind, that brew's going to fork the repository and need credentials to do so, but github token will do, which you could assign to env variable `HOMEBREW_GITHUB_API_TOKEN`

That approach has to be tested before using in production drone, of course, and some tinkering required, perhaps.

**Comment by Jeffail** [comment]
Okay awesome, I'll give this a go for the v3.8.0 release (hopefully later this week).

**Comment by Jeffail** [comment]
https://github.com/Homebrew/homebrew-core/pull/49227, did it manually this time but I'll add it to the goreleaser config for the next release.

**Comment by Jeffail** [comment]
Closed for now, I'm still doing this as a manual step after each release as I'm not feeling confident I understand what goreleaser would be doing.
