### ISSUE TITLE
Injecting Jaeger Span Id into Headers

### ISSUE THREAD

**Issue by kozelok** [Jeffail/benthos#416]
Hello,

Currently I'm essentially using a temp map as Injection destination, and then setting value on metadata. 

opentracing.GlobalTracer().Inject(
			span.Context(),
			opentracing.TextMap,
			opentracing.TextMapCarrier(tempMap),
		)

part.Metadata().Set(uberTraceId, tempMap[uberTraceId])

Is there a better way to Inject jaeger parent spanId into Metadata?  

Thank you!

**Comment by Jeffail** [comment]
Hey @kozelok, my knowledge of the opentracing API is pretty limited so I'm not sure, I'll leave this open in case anyone else can chime in.

**Comment by mfamador** [comment]
Hi @kozelok and @Jeffail!
I've created a custom processor in which I set a `metadata_key` (defaults to `trace_id`) from my choice with the traceID:
```
if sc, ok := span.Context().(jaeger.SpanContext); ok {
  t := sc.TraceID()
  part.Metadata().Set(p.conf.MetadataKey, t.String())
}
```
I think this could be configured somehow in the tracer config, but this way if working perfectly for my use case.
Let me know if you'd like me to create a PR with it you find it useful.
Cheers

**Comment by willwolfram18** [comment]
> Hi @kozelok and @Jeffail! I've created a custom processor in which I set a `metadata_key` (defaults to `trace_id`) from my choice with the traceID:
> 
> ```
> if sc, ok := span.Context().(jaeger.SpanContext); ok {
>   t := sc.TraceID()
>   part.Metadata().Set(p.conf.MetadataKey, t.String())
> }
> ```
> 
> I think this could be configured somehow in the tracer config, but this way is working perfectly for my use case. Let me know if you'd like me to create a PR with it if you find it useful. Cheers

@mfamador @Jeffail would you be able to share a link or complete code sample for how to write this plugin? I would love to be able to put a trace and/or span Id into the `meta()` object and include it in any log messages I write so that our APM/logging platform can auto correlate traces and log events 👍 Right now the benthos plugin documentation is a little difficult to navigate for a newbie (granted I'm also a Go newbie so I'm still getting my sea legs with that at the same time).

Any help would be appreciated!
