### ISSUE TITLE
Looking for a way to decode HTML entities in XML file.

### ISSUE THREAD

**Issue by jalajarora** [Jeffail/benthos#432]
We are using the XML processor https://www.benthos.dev/docs/components/processors/xml
Though the conversion fails and returns the same XML back when the XML content contains HTML entities such as `&amp;`, `&lt;`, `&ndash;`, `&circ;` etc...

So, maybe the XML processor itself could also handle UnescapeString?

**Comment by Jeffail** [comment]
Hey @jalajarora, I can solve this partially by setting the XML parser to be less strict, so that when it sees escape sequences it doesn't recognize (the majority of HTML escapes) it will simply pass them through unescaped. This will allow your documents to get parsed, but it also means the escape sequences will remain in the string values. In order to temporarily work around that I'll add a method `unescape_html` which you can use on those field values.

Unfortunately, the library I'm using to do the conversions forces this `strict` configuration to be set globally and so I can't expose it as a configuration field. The `xml` processor is still marked as experimental and so I think it makes sense to do this even though it's technically a breaking change as it will unblock cases such as these.

My plan is to make these changes today and get a release out for you to try, then eventually I'll need to either help refactor the upstream library or fork it in order to be more flexible with the XML parsing.

**Comment by Jeffail** [comment]
For unescaping all string values in the resulting JSON document you'll be able to do:

```
pipeline:
  processors:
  - xml:
      operator: to_json
  - bloblang: |
      map unescape_values {
        root = match {
          this.type() == "object" => this.map_each(this.value.apply("unescape_values")),
          this.type() == "array" => this.map_each(this.apply("unescape_values")),
          this.type() == "string" => this.unescape_html(),
          this.type() == "bytes" => this.unescape_html(),
          _ => this,
        }
      }
      root = this.apply("unescape_values")
```

**Comment by Jeffail** [comment]
Released: https://github.com/Jeffail/benthos/releases/tag/v3.16.0

**Comment by jalajarora** [comment]
Thank you @Jeffail 
I will try this out.
