### ISSUE TITLE
Question - Kafka Output

### ISSUE THREAD

**Issue by kozelok** [Jeffail/benthos#456]
Hello,

Wanted to ask about performance tuning. Having an issue with data not being pushed out to kafka fast enough. 

I am running benthos in streams mode. 4 streams.

stream 1: 3X MQTT input, simple filter pipeline, 2x Broker: Kafka Output with Greedy, snappy compression, max in flight=10
stream 2: 3X MQTT input, simple filter pipeline, 2x Broker: Kafka Output with Greedy, snappy compression, max in flight=10
stream 3: 3X MQTT input, simple filter pipeline, 2x Broker: Kafka Output with Greedy, snappy compression, max in flight=10
stream 4: 3X MQTT input, simple filter pipeline, 2x Broker: Kafka Output with Greedy, snappy compression, max in flight=10

Few questions:
1.  I noticed number of system threads does not increase with additional streams, is this expected?
2. The latency base is quite high, almost 20ms(Latency Readable from MQTT brokered input), why would this happen? I tested with drop:{} output, and this number becomes nanoseconds.
3. Is there any additional tuning to increase the output?

**Comment by Jeffail** [comment]
Hey @kozelok, it sounds like you're bottlenecked by the output which will limit how much you can utilize processing threads due to the back pressure. With kafka you'll generally see the best performance gains by sending messages as batches.

My advice would be to remove the broker and have a single kafka output with both batching and a max in flight:

```yaml
output:
  kafka:
    addresses:
      - localhost:9092
    topic: foo
    max_in_flight: 10 # Try tuning this second
    batching:
      count: 20 # Try tuning this first
```

I'd first try increasing/decreasing the batch size and then once you've found the best fit move onto increasing/decreasing the max in flight parameter. The `max_in_flight` parameter is a more efficient way of getting the async message delivery gains you'd see with a greedy broker, which is why I'd recommend taking it out.

**Comment by kozelok** [comment]
Thank you Jeff. I added batching to the config.

A parallel question:
1. Is batching in the input broker same as batching in the kafka output? My understanding is that the batcher.go is the same for both.
2. Is there any way to tune the max number of go-routines generated?

**Comment by Jeffail** [comment]
Hey @kozelok,

1. The functionality is the same, the difference is that doing the batching at the input level allows the kafka input to batch messages individually for topic partitions, allowing them to be batch processed in order.
2. It's not possible to set a global limit but you can indirectly control the number of goroutines by limiting the number of inputs, processing threads and outputs. When you increase the field `max_in_flight` of an output you'll increase the number of goroutines.
3. Unfortunately using sarama to asynchronously batch and dispatch messages prevents Benthos from propagating acknowledgements up to the input level for ensuring delivery guarantees.
