### ISSUE TITLE
Bloblang processor error when using 'without' method

### ISSUE THREAD

**Issue by paulrwalton66** [Jeffail/benthos#490]
Using the latest release 3.24.1.
I have the following object read from SQS:
{
        "DeviceChannel" : "XXX",
        "DeviceId" : "nnnnnnnn",
        "DeviceEventId" : "3af5175c-1b6f-4cd1-9d6f-27e152795b12",
        "ReceivedUtc" : "2020-08-15T19:46:52Z",
        "PacketId" : 0x00,
        "MessageName" : "Report",
        "ParsedMessage" : {
                "eventType" : "yyy",
                "format" : "zzzz",
                "data" : {
                        "arr" : [{
...
                        }],
                        "timestamp" : 1597520812,
                }
        },
        "BlockList": null
}
My config has the following pipeline defined:
pipeline:
  processors:
  - bloblang:  root.msg = this.without("BlockList")

When benthos attempts to process the message I am getting the following ERROR:
{"@timestamp":"2020-08-15T13:46:55-06:00","@service":"benthos","level":"ERROR","component":"benthos.pipeline.processor.0","message":"failed to execute mapping assignment at line 1: context was undefined"}
I have tried all sorts of different ways to remove the Json node including the deleted() method, but I always seem to get the same type of Error when the 'this' keyword is used.
I am new to Benthos and really like what it can do, just getting a bit frustrated with the lack of useful information on what the cause of the error might be and why. Would appreciate some help, thanks!

**Comment by Jeffail** [comment]
Hey @paulrwalton66, this is most likely due to it failing to JSON parse the input messages and unfortunately the actual parsing error is being stripped. I've fixed the error stripping (https://github.com/Jeffail/benthos/commit/d523dff17ccd96033ef976fdd4408a35628a1f0c) so in the next release (hopefully this weekend) you'll get a proper error message.

In the meantime you should be able to expose it with version `3.21.1` by changing `this.without("BlockList")` to `json().without("BlockList")`, and then you'll hopefully get a more useful error message, something like `failed to execute mapping query at line 1: invalid character 'f' looking for beginning of object key string`.

**Comment by Jeffail** [comment]
Just spotted your JSON example has a hex value in it `"PacketId" : 0x00`, this is most likely what's causing the failed parse as the Go JSON parser doesn't support JSON5 hexadecimal values (yet). If you're able to prevent those values from appearing in your messages then that's the easiest solution, otherwise we'll need to work around it.

**Comment by paulrwalton66** [comment]
Hi Ashley,
Firstly thanks for the quick response. I just modified the PacketId to be an integer instead of a hexadecimal value and my processing works just like that bam! I also notice now that my output has changed and it looks like previous it was simply printing the input message following the processor failure. Keep up the good work!
So not only i am new to Benthos and Goland but I am also new to github and was wondering if submitting an issue is the best way to confirm my understanding especially as i want to do more with the bloblang processor and outputs in the future.

**Comment by Jeffail** [comment]
Hey @paulrwalton66, for general questions it's best to use either our gitter or slack channels, links for both are at the bottom of the project readme: https://github.com/Jeffail/benthos#contributing

**Comment by Jeffail** [comment]
Closing for now, version [3.15.0](https://github.com/Jeffail/benthos/releases/tag/v3.25.0) is out with the error message fix, but feel free to reopen if you have any follow up questions.
