### ISSUE TITLE
Ristretto disable retries/backoff

### ISSUE THREAD

**Issue by iluminae** [Jeffail/benthos#534]
I want to use the upstream ristretto cache (instead of the plugin version we wrote) but the retries/backoff in the upstream version are unwanted, and it does not _appear_ that you can completely disable it? Setting max_retries=0 makes it retry indefinitely, how can I disable this functionality?

Further, I understand the non-atomic nature of the cache is different than other caches in benthos, but I do not quite understand this as a default for this cache. If you perform a cache Get() and it fails, thats a valid response and can still be part of a high-speed pipeline and not a 30s wait. Stated differently, I do not think the default for a cache should be to assume the cache will have the key you are asking for.

Thanks!

**Comment by Jeffail** [comment]
Hey @iluminae, yeah we definitely need to be able to disable retries here. I'd be happy to change it to interpret 0 retries as disabling them altogether, it's a beta component so we can change the behaviour if there's a fundamental problem and I think this fits. As for the defaults I'm also happy to have them disabled by default, although my first instinct was to have them enabled in order to avoid confusion over why setting a value and immediately getting it back might fail, but we can use documentation to fill that void.

**Comment by iluminae** [comment]
Excellent, thank you.

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/3f9fc727eba2ea2c91f9178d91ea076cf3492a3f

**Comment by Jeffail** [comment]
Released: https://github.com/Jeffail/benthos/releases/tag/v3.32.0
