### ISSUE TITLE
Allow TLS on Redis Cache

### ISSUE THREAD

**Issue by eduardodbr** [Jeffail/benthos#535]
Hi!

We are thinking about using Azure Redis to do caching but right now the redis cache resource does not support TLS connections. We have two options, disable TLS on azure (which is not advised) or enable TLS on benthos. I already did some testing and the simplest way to enable TLS on Redis Cache is to do add the `TLSConfig` to the client with `InsecureSkipVerify: true` :

```
client := redis.NewClient(&redis.Options{
		Addr:     url.Host,
		Network:  url.Scheme,
		DB:       redisDB,
		Password: pass,
		TLSConfig: func(useTLS bool) *tls.Config {
			if useTLS {
				return &tls.Config{InsecureSkipVerify: true}
			}
			return nil
		}(useTLS),
})
``` 

This config enables SSL but by setting `InsecureSkipVerify`, TLS accepts any certificate presented by the server and any host name in that certificate. This might be a security flaw but my knowledge of the field isn't enough to add more content to the resource (like certificates), so feel free to add comments/improvements.

Even so, I believe that enabling TLS with `InsecureSkipVerify` is still better than no TLS at all,  what do you think?

**Comment by Jeffail** [comment]
Hey @eduardodbr, there's a general purpose TLS struct that can usually be recycled, I assume that's the case here as well so we should be able to quickly add the same fields as here for example: https://www.benthos.dev/docs/components/inputs/kafka#tls.

I can probably make time to add this myself this week, otherwise if you or someone else wants to take a look there's a good example of it being used here: https://github.com/Jeffail/benthos/blob/master/lib/input/amqp_1.go
