### ISSUE TITLE
Allow resource updates in streams mode

### ISSUE THREAD

**Issue by joe-getcouragenow** [Jeffail/benthos#566]
its mentioned at the bottom of this section: https://www.benthos.dev/docs/guides/streams_mode/about#resources

Wondering that the status .. Remind me of Caddy, which is able to update the config in real time. There might be a way to use the technique caddy uses. Caddy forks the process so the new process runs against the new config any the old ones are let to complete. https://caddyserver.com/docs/architecture#caddy-core

**Comment by Jeffail** [comment]
Hey @joe-getcouragenow, yeah this is definitely on the (soon to be finalized and published) roadmap. We have an existing issue for general config file reloading: https://github.com/Jeffail/benthos/issues/338 which isn't blocked on V4, but in order to have a resources CRUD API in streams mode there would be some changes that require V4 in order to have non-atomic usage of resource components work.

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/5c2496b5eaedf3b5929dd818e5b838451c627e80, there's now an endpoint where you can POST a new config for a resource, which will replace the existing one if there is one. It's pretty basic right now, you can't do a GET to obtain the current config or anything, but it's the important part.
