### ISSUE TITLE
Azure Blob Storage input

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#582]
Thank you for this awesome project! I have a use case where I need Benthos to have the Azure Blob Storage input, but, for now, it only seems to have the output, which was added in #466 and refined in #514.

As @mfamador mentioned [here](https://github.com/Jeffail/benthos/pull/514#issuecomment-703555640), this would also be beneficial for having integration tests (using [Azurite](https://github.com/Azure/Azurite)).

I am thinking of writing the code to add this input and upstreaming the changes in a PR, if you're interested in having such a contribution.

Would that be of interest to you?

**Comment by Jeffail** [comment]
Hey @mihaitodor, yeah this totally makes sense. I'm not too familiar with blob storage but I'm assuming this would be a "walk the directory and pull each file seen, then close" type of job. I would imagine a lot could be copied from the new [`aws_s3`](https://github.com/Jeffail/benthos/blob/master/lib/input/aws_s3.go) input, although there's logic there for streaming SQS notifications that wouldn't need copying over. Although if there's a possibility for downloading from blob storage based on upload notifications that'd be nice to add at some point as well.

**Comment by mfamador** [comment]
Hi @Jeffail and @mihaitodor!
Great, this is something I was planning to do for a while, but since I don't have a real use case, for now, I've been postponing it. If you need any help on this just let me know, please.
You probably already know, but If you want to mimic the same behaviour of emitting upload notification events from the container to a queue as in AWS S3/SQS, you might want to have a look to Azure Event Grid where we can also subscribe the events from uploading to blob storage and send them to a Storage Queue, for example. Here's an example setting this up, in which I believe we'd just needed to change the event handlers from Web Hook to Storage Queues: https://docs.microsoft.com/en-us/azure/event-grid/blob-event-quickstart-portal
Cheers

**Comment by mihaitodor** [comment]
@Jeffail @mfamador Thank you for the quick replies! For now, we're thinking to go with the "walk the directory and pull each file seen, then close" option and leave the Event Grid + Storage Queue part as a future enhancement. Will keep you posted.
