### ISSUE TITLE
S3 / Azure input codecs and memory usage

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#599]
Say, for example, somebody wants to use Benthos to transfer arbitrary binary files from S3 to Azure that can vary in size by orders of magnitude.

I was looking into the [downloading large files](https://www.benthos.dev/docs/components/inputs/aws_s3/#downloading-large-files) section of the docs and started wondering how would one constrain Benthos' memory in this particular case. Using `all-bytes` as a codec will make it blow up when encountering a large file, since it tries to read the whole file in memory, if I understand [the code](https://github.com/Jeffail/benthos/blob/0ff54f67463de7516afb25307785684b23595693/internal/codec/reader.go#L170) correctly.

Would adding something like a `chunker:size` codec make sense? It would be similar to `delim:x`, but `size` would be in a format which can be parsed into bytes (using a helper lib such as [this one](https://github.com/alecthomas/units)).

**Comment by Jeffail** [comment]
Hey @mihaitodor, yeah I think for that we would want something like `chunker:size`. Benthos is perfectly happy to gobble up binary data so processor pipelines and everything else should be fine.

At the output level we would need an instruction of some sort to say that our intention is to append the data to an open file rather than replace it, this type of behaviour is already supported with the file output: https://www.benthos.dev/docs/components/outputs/file. However, with networked outputs like s3 and azure we need a clean solution to the problem of how long to keep the connection alive for. When the target filepath changes we can close the current one, but in the event of data stopping momentarily we need a mechanism for closing the connection after a certain period.

I would want to avoid situations where someone is writing data from X to Y, pipes some data through and is then confused as to why the data at Y hasn't been updated (benthos is still holding the connection open, assuming to write more data).

**Comment by mihaitodor** [comment]
@Jeffail Thanks for sharing your thoughts!

> However, with networked outputs like s3 and azure we need a clean solution to the problem of how long to keep the connection alive for. When the target filepath changes we can close the current one, but in the event of data stopping momentarily we need a mechanism for closing the connection after a certain period.

Naively, without looking through the code, I was thinking that there would be some channel mechanism inside the the `types.Message` [implementation](https://github.com/Jeffail/benthos/blob/f47911115aa2e8efd3f6ed9b94f9ea163fff87fc/lib/message/message.go#L13) and then [IterateBatchedSend](https://github.com/Jeffail/benthos/blob/6ef84e5713f867a847d417e969055f4d9620b968/lib/output/writer/batched_send.go#L31) would be able to iterate on message parts coming through that channel (maybe via [`Message.Iter()`](https://github.com/Jeffail/benthos/blob/f47911115aa2e8efd3f6ed9b94f9ea163fff87fc/lib%2Ftypes%2Fmessage.go#L124)) or stop and close the output if it detects that this channel was closed or a timeout was reached. Currently, the output writes are [driven by transactions](https://github.com/Jeffail/benthos/blob/2008eaf72c82f5cd32504621a2ade9ad8e13b17e/lib%2Foutput%2Fasync_writer.go#L171) so not sure if such an approach would fit in, but I'm curious if this is a design you'd consider.

> I would want to avoid situations where someone is writing data from X to Y, pipes some data through and is then confused as to why the data at Y hasn't been updated (benthos is still holding the connection open, assuming to write more data).

Yeah, that can be annoying... Looks like S3 [doesn't support](https://stackoverflow.com/questions/41783903/append-data-to-an-s3-object) appends to files, so not sure if it would be possible to flush the contents every x seconds. Maybe some reasonably small timeouts would suffice.

**Comment by mihaitodor** [comment]
Update: I added the `chunker` codec via 640# and I fixed the `APPEND` blob support for Azure in #639. For S3, since it doesn't have any append support, I think there is still value in having this codec if users are interested in storing the chunks as separate files. I think this has precedent if we consider multipart archives, for example. Not sure what would be the best way to document how this codec can be used in combination with the various outputs.

Also, another thought: If one can accept writing each chunk to a separate file, then the `max_in_flight` field can be used to transfer multiple chunks in parallel and increase throughput.
