### ISSUE TITLE
Facing issue in json set processor

### ISSUE THREAD

**Issue by sathiya-mit** [Jeffail/benthos#60]
{
  "data":  {
      "className": "foo",
      "packageName": "bar"
   }
}

In the above JSON I need to add one more attribute like below

{
  "data":  {
      "className": "foo",
      "packageName": "bar"
   },
   "startedBy": "user1"
}

What should I provide in 'path' ? Tried providing dot(.) to 'path' as mentioned below. It didn't work as expected.

processors:
  - type: json
    json:
      operator: set
      parts: []
      path: "."
      value:
        startedBy: user1
  threads: 1

**Comment by sathiya-mit** [comment]
Appreciate your help !!!

**Comment by Jeffail** [comment]
Hey @sathiya-mit, try:

``` yaml
type: json
json:
  operator: set
  path: startedBy
  value: user1
```

When you set `path: "."` you are telling the processor to set the contents of the root object to `value`, which would make the result `{"startedBy":"user1"}`, but what you actually want to do is set the value of `startedBy` to `"user1"`, and so that path you set is just that field name and the field will be created if it doesn't already exist (which in this case it doesn't).

**Comment by sathiya-mit** [comment]
Thanks a ton @Jeffail  Appreciate your help !!! It worked like charm. I want to add one more value as mentioned below and I got it working by adding one more json processor. Please let me know if there is a better way to do it.

{
"data": {
"className": "foo",
"packageName": "bar"
},
"startedBy": "user1",
"endedBy": "user2"
}

**Comment by Jeffail** [comment]
You could also do it with a single [jmespath](https://github.com/Jeffail/benthos/tree/master/docs/processors#jmespath) query:

``` yaml
type: jmespath
jmespath:
  query: |
    merge(@, {startedBy:'user1', endedBy:'user2'})
```

But I would put it down to personal preference, whichever is clearer to you.
