### ISSUE TITLE
Optionally prevent overwrite with file output

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#628]
Looking at the [file output](https://www.benthos.dev/docs/components/outputs/file), I was wondering if there's any way to prevent accidental overwrites. I'm thinking to have a config parameter for it which, if true, forces the output to first check if the file exists and, if it does, bail out. Looking at the [WriterConfig](https://github.com/Jeffail/benthos/blob/18afcaae20f7849d630d376ef64daa5ed43b195d/internal/codec/writer.go#L37-L41), I'm not entirely sure what would be the best semantics, if, say, `Truncate == true`.

**Comment by Jeffail** [comment]
I think that'd be fairly straight forward to add, we'd want to make that check further up the stack than at the codec level so we wouldn't need to touch the writer config. Just add a boolean field to the output config to do a stat on the path here: https://github.com/Jeffail/benthos/blob/master/lib/output/file.go#L144.

I think in terms of "failure" since the path is an interpolation field we should consider a file collision to be a send error local to the message, if we return an explicit error from the write then it allows the user to tune their own behaviour for their use case. E.g. if the path is meant to be random then by default we'd simply try the same write again with a new interpolation, but alternatively you could do something like add a DLQ with a `try` broker that writes the message somewhere else (or logs).

**Comment by mihaitodor** [comment]
Closing in favour of #802.
