### ISSUE TITLE
How to filter out Kafka tombstones using bloglang?

### ISSUE THREAD

**Issue by drurenia** [Jeffail/benthos#663]
I have some topics with tombstones which I can't seem to find a way to filter them out. The following is the code without any filterning attempts followed by different approaches I've tried:

```javascript
root.doc = this
root.key = meta("kafka_key").parse_json()
root.topic = meta("kafka_topic")
```

Approach 1:

```javascript
root.doc = this.or([])
root.key = meta("kafka_key").parse_json()
root.topic = meta("kafka_topic")
root = match {
    root.doc.length() == 0 => deleted()
}
```

Approach 2:

```javascript
root.doc = this
root.key = meta("kafka_key").parse_json()
root.topic = meta("kafka_topic")
root = match {
    root.doc == null => deleted()
}
```

Approach 3:

```javascript
root.doc = this.parse_json().or([]).catch([])
root.key = meta("kafka_key").parse_json()
root.topic = meta("kafka_topic")
root = match {
    root.doc.length() == 0 => deleted()
}
```

None of the above helped and they even filtered out records that were not tombstones.

The errors: 

``` 
{"@timestamp":"2021-02-11T08:11:16Z","@service":"benthos","error":"failed to execute mapping query at line 1: failed to parse message as JSON: target message part does not exist","from_topic":"Topic-A","payload":"null","level":"ERROR","component":"benthos.pipeline.processor.1.0","message":"Error while processing a message"}
``` 

```
{"@timestamp":"2021-02-11T08:11:16Z","@service":"benthos","level":"ERROR","component":"benthos.pipeline.processor.0","message":"failed to execute mapping query at line 1: failed to parse message as JSON: target message part does not exist"}
``` 

What am I missing here?

**Comment by Jeffail** [comment]
Hey @drurenia, when you refer to a message with `this` Bloblang will attempt to parse the message as a structured object, but in the case of tombstone messages I believe the contents themselves are empty, which makes it invalid JSON and the mapping throws an error. The error message you receive is a bit cryptic (claiming there is no message part, when there actually is, it's just empty).

However, you can catch the error in order to prevent the mapping from failing, and then use the [`content()` function](https://www.benthos.dev/docs/guides/bloblang/functions#content) to refer to the raw contents of messages for your filter mechanism:

```coffee
root.doc = this.catch([])
root.key = meta("kafka_key").parse_json()
root.topic = meta("kafka_topic")
root = if content().length() == 0 {
  deleted()
}
```

There's a few things I can improve here, the first being that error message. The second thing I can do is allow `deleted()` as a `catch` argument, which would allow you to simplify this down to:

```coffee
root = {"doc": this}.catch(deleted())
root.key = meta("kafka_key").parse_json()
root.topic = meta("kafka_topic")
```

Which would also catch invalid JSON documents at the same time.

**Comment by drurenia** [comment]
Hey @Jeffail, indeed I was missing the `content()` part of it all and it did the trick for me.

Supporting `deleted()` as a catch argument is indeed much cleaner (+1)

Thank you once again for the fast and spot on answer!

**Comment by Jeffail** [comment]
Support for `.catch(deleted())`: https://github.com/Jeffail/benthos/commit/f771458e197681e9b86a5fe0a4371ad7ffae3b29
Improved error messages: https://github.com/Jeffail/benthos/commit/e9b5cd391dafe9415937526ecb2039983bfe7d52
