### ISSUE TITLE
Benthos is blocked during shutdown

### ISSUE THREAD

**Issue by yev-dimo** [Jeffail/benthos#675]
Using streams mode, and each one polling a different endpoint. Shared rate_limit for all 3. No issues at runtime, but during shutdown:

[errorLog.txt](https://github.com/Jeffail/benthos/files/6006106/errorLog.txt)

**Comment by yev-dimo** [comment]
One addition, this seems to happen with any rate_limit specified. Removing rate limit fixes the issue(but is needed)

**Comment by Jeffail** [comment]
Hey @yev-dimo, this isn't a crash it's just informing you that when attempting to gracefully shut down the service there's a component that wanted to stay alive longer than Benthos was willing to wait. The reason for that is because your rate limit has blocked the http component. If you can provide more information about your configuration then I can look into this some more, but what you're seeing isn't a problem (other than needing to wait for longer for Benthos to shut down).

You can increase the shutdown timer for Benthos with the field `shutdown_timeout`: https://github.com/Jeffail/benthos/blob/master/config/amqp_0_9.yaml#L78

**Comment by yev-dimo** [comment]
That explain it! Thank you!
