### ISSUE TITLE
ExpiredIteratorException in aws_kinesis

### ISSUE THREAD

**Issue by parisholley** [Jeffail/benthos#735]
https://github.com/Jeffail/benthos/issues/139 - I believe this bug is an issue now in the latest input type (aws_kinesis) vs legacy, or perhaps my use-case is slightly different.

If I have kinesis -> kafka, and my kafka broker goes down (or any output for that matter) for more than 5 minutes, benthos will not recover. I would assume it should attempt to get a new iterator if the old one has expired.

**Comment by Jeffail** [comment]
Hey @parisholley, I _believe_ this should fix the issue https://github.com/Jeffail/benthos/commit/fc0a839c76843b24c8ea043b2c6fe2eb19f48979, if you could test and verify that'd be great, otherwise I'll try and make time to set up a test environment this week. If you still see that Benthos stalls then post any logs you get here, and if there isn't much to go by then it might be worth enabling debug http endpoints https://www.benthos.dev/docs/components/http/about#debug-endpoints and posting the result of `/debug/stack`.

**Comment by parisholley** [comment]
think that did it, rebooted the services without clearing the dynamodb state and it didn't error

**Comment by Jeffail** [comment]
Cool, thanks @parisholley, are you blocked on a proper release with this included? I'll likely tag a release early next week but I can bring that forward if you need. Closing for now but please reopen if you notice it again.

**Comment by parisholley** [comment]
not blocked, i run github builds anyway
