### ISSUE TITLE
Can we get also a driver for MS sql server?

### ISSUE THREAD

**Issue by AdrianLsk** [Jeffail/benthos#797]
Hello, I would love to use benthos in a project using MS SQL server.

It would be really great if there was support also for this database driver.

Do you have any plans for it / Would it be hard to add support for it?

Cheers

**Comment by Jeffail** [comment]
Hey @AdrianLsk, it looks as though it's a case of importing a driver (https://github.com/denisenkom/go-mssqldb looks like the one) and then adding it to the docs. I'm not sure there's a solution for integration tests since we'd need a containerized instance of MS SQL server which I doubt is offered anywhere :sweat_smile:, so I'd need you to try it out and report back whether it's functional.

**Comment by AdrianLsk** [comment]
Hi @Jeffail, cool, that doesn't sound too complicated.

It shouldn't be a problem to do integration tests either. It's possible to use free dev version of SQL server. For example, they provide this [docker-compose](https://github.com/microsoft/sql-server-samples/blob/master/samples/development-frameworks/SqlServerOnDocker/docker-compose.yml) (or just its [Dockerfile](https://github.com/microsoft/sql-server-samples/blob/master/samples/development-frameworks/SqlServerOnDocker/docker/db/Dockerfile)) for a sample app with SQL server on the backend. Would it be good enough for the tests?

**Comment by mihaitodor** [comment]
Hey @AdrianLsk I created a PR (#798) for this and once @Jeffail has some time to review it this should be good to go :)

**Comment by AdrianLsk** [comment]
Hey @mihaitodor, great! Thanks a bunch for the speedy work. 🙏
