### ISSUE TITLE
Inconsistent metadata keys when using S3 as input

### ISSUE THREAD

**Issue by elundblad** [Jeffail/benthos#806]
On 3.47.0, user defined metadata from S3 can't be referenced or deleted when using lowercase metadata keys.

Steps to reproduce:
1. Upload an object to S3 with user metadata, e.g. `x-amz-meta-testkey`
2. Setup benthos with S3 as input
3. Try to delete the metadata using bloblang or the metadata operator, e.g. `meta testkey = deleted()`
4. Send the object to an S3 output

Expected result: 
testkey is removed

Actual result: 
testkey is preserved

The same scenario applies when e.g. overwriting metadata, for example `meta testkey = "overwrite"` will just append `overwrite` to the existing metadata. What works however is a key with a capital letter, e.g. `meta Testkey = deleted()`.

Can this be improved? Thanks

**Comment by Jeffail** [comment]
Hey @elundblad, I believe this is because in AWS the metadata keys are case insensitive, and when they're received they are changed to be capitalized for some reason. I'm not sure if there's anything I can do to stop that without breaking changes, but you can rename the metadata keys to force them into lowercase with the following mapping:

```yaml
input:
  aws_s3:
    bucket: TODO
  processors:
    - bloblang: 'meta = meta().map_each_key(key -> key.lowercase())'
```

I'll mark this as a documentation issue as it should be made clear in the input docs.

**Comment by Jeffail** [comment]
Updated docs: https://github.com/Jeffail/benthos/commit/2b7e7eacf6296403875662a0665595b1bcd57f43
