### ISSUE TITLE
Move to new opentelemetry tracing APIs

### ISSUE THREAD

**Issue by edude03** [Jeffail/benthos#872]
Hello,

I'm currently monitoring benthos using Jaeger and It seems that benthos doesn't set the span status (for example `Span.Status: ERROR`). 

This would be useful for me as in the case benthos errors on processing a message, it would be nice to be able to find out that it failed, and as well have metadata about the failure for debugging.

**Comment by Jeffail** [comment]
Hey @edude03, looks like we're currently doing a half-baked version of this by setting a tag with `span.SetTag("error", true)`. There's a rough plan to migrate the internal mechanisms for tracing to use the newer opentelemetry APIs (when there's a stable release) so I'll probably hold off on changes to tracing until then, but it makes sense to tackle this at the same time.

**Comment by mfamador** [comment]
Hi! 
I guess there's already a stable version: https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.0.0

**Comment by cristiprg** [comment]
Hi @Jeffail @mfamador it would be really useful to have Open Telemetry support. The go package is getting fairly stable, already at v1.3.0. 

Is the any plan to migrate Benthos to Telemetry anywhere near on the roadmap? Reading the comments [here](https://github.com/Jeffail/benthos/blob/master/internal/tracing/package.go), seems the foundation is there for the migration.

**Comment by Jeffail** [comment]
@cristiprg, it's in motion, the work within https://github.com/Jeffail/benthos/commit/5983fd73b539eb011f4ce779fa88e82c26bde483 was to prepare internal components for the migration, there's some outstanding work on translating the jaeger exporter: https://github.com/Jeffail/benthos/tree/opentelemetry, one outcome so far is that we can't support all the same sampling mechanisms with otel.

The main outstanding problem is backwards compatibility. It'd be a huge effort to support both mechanisms at the same time, so realistically we'd want to ditch the current opentracing support. This means we need a major version release, there's one on the way but I'm holding it off in order to give time to plugin authors using the old APIs.

**Comment by Jeffail** [comment]
Effort done here: https://github.com/Jeffail/benthos/commit/545d124b42ad7ae9441edd7d51149ca43a67cc25, this is only so far as it compiles and needs testing.

**Comment by Jeffail** [comment]
Ready in v4: https://github.com/Jeffail/benthos/commit/697813c58d15722c7acae95b0ccfbbcdf8b14b27
