### ISSUE TITLE
Proposal: Add Flexibility to TLS Configuration

### ISSUE THREAD

**Issue by ghballiet** [Jeffail/benthos#91]
In addition to loading TLS certificates and keys as files, we need to be able to load keys and certs from strings directly.

**Comment by Jeffail** [comment]
Merged, I'm worried that because this config section is within an array it's not documented anywhere. I'm not sure what a clean solution would be since this config section will appear in lots of different places.

We could either create a static markdown file in `./docs` specifically explaining the tls config format and then refer to it in any types that use it, which is tedious and won't automatically keep up with changes.

Alternatively, when we initialise a new `tls` struct we could always drop in a single element with all fields empty. This would result in any generated config examples containing the full structure and it would be self documenting. However, we would need to treat a client certificate with all empty fields as if it didn't exist, which seems a little bit dirty.

**Comment by Jeffail** [comment]
Okay I think I found a middle ground for documentation.
